services:
  - type: web
    name: quickcv-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://quickcv-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html